Featured collection  image with text  richtext сarousel
Wuffes/wuffes-2.0 pull request #1
Opened 2024-06-03 16:53 UTC by mikhail-wuffes

### PR Summary: 

### Why are these changes introduced?

Fixes #0.

### What approach did you take?

### Other considerations

### Decision log

| # | Decision | Alternatives | Rationale | Downsides |
|---|---|---|---|---|
| 1 |   |   |   |   |

### Visual impact on existing themes

### Testing steps/scenarios

- [ ] Step 1

### Demo links

- [Store]([preview link](https://wuffes.com/pages/about-us?view=misha_test&preview_theme_id=129319698567))
- [Task](https://app.asana.com/0/1206375175000843/1207472887984490/f)

### Checklist
- [ ] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [ ] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

2024-06-05 17:52 UTC, alex-wuffes requested changes
@mikhail-wuffes Apply fixes in this doc along with metafields changes, and we're good to go.

2024-06-05 17:52 UTC, alex-wuffes commented on sections/featured-collection.liquid
> +            aria-label="{{ 'general.slider.name' | t }}"
Remove redundant comments. Don't leave it in the code. We can restore it anytime by looking into the original repo

2024-06-05 17:52 UTC, alex-wuffes commented on sections/image-with-text.liquid
> +              </div>
block.shopify_attributes have to be in the block wrapping block
```suggestion
              <div
                class="image-with-text__decoration"
                {{ block.shopify_attributes }}
              >
                <h2
                  class="image-with-text__heading image-with-text__heading_above inline-richtext {{ block.settings.heading_size }}"
                  {% if block.settings.no_margins %}
                    style="margin: 0;"
                  {% endif %}
                >
                  {{ block.settings.heading }}
                </h2>
                <div
                  class="image-with-text__media-decorate"
                  style="background: {{ section.settings.color_scheme.settings.button }};"
                ></div>
              </div>
```

2024-06-05 17:52 UTC, alex-wuffes commented on sections/image-with-text.liquid
>                    <p
Include block.shopify_attributes. Also, please, fix it across the whole PR. Every block implementation has to have the block.shopify_attributes variable in the wrapper block

2024-06-05 17:52 UTC, alex-wuffes commented on snippets/card-product.liquid
Misha, you added new variables to this snippet. It means you have to update the documentation in the top of the file. Apply to others in case there are any

2024-06-05 17:52 UTC, alex-wuffes commented on sections/image-with-text.liquid
> +                  (min-width: 750px) calc((100vw - 130px) / 2), calc((100vw - 50px) / 2)
You updated the page margins. It means "sizes" for images have to change. 
For example, mobile has to change to calc((100vw - 50px) / 2)

ACTUALLY, I don't get it why it's calc((100vw - 50px) / 2), but not calc(100vw - 50px) in dawn theme. That's really strange, and I don't get it. I think we can leave this for later

2024-06-05 17:52 UTC, alex-wuffes commented on snippets/card-product.liquid
> +                sizes="(min-width: {{ settings.page_width }}px) {{ settings.page_width | minus: 30 | divided_by: 4 }}px, (min-width: 990px) calc((100vw - 30px) / 4), (min-width: 750px) calc((100vw -
https://www.loom.com/share/2828d04c679d4f4b84b02b953513c93f?sid=37bce903-0093-4d4c-83d7-b8998cb501fa

2024-06-05 17:52 UTC, alex-wuffes commented on snippets/card-product.liquid
> +                sizes="(min-width: {{ settings.page_width }}px) {{ settings.page_width | minus: 30 | divided_by: 4 }}px, (min-width: 990px) calc((100vw - 30px) / 4), (min-width: 750px) calc((100vw -
Following up on the issue I discovered in the loom above: 
It looks like product-card was intended to be a universal block, but in the featured collection image sizes are not adequate.
We can use the recommendations from this [issue](https://github.com/Shopify/dawn/issues/1738) to fix that

2024-06-05 17:52 UTC, alex-wuffes commented on snippets/icon-minus-circle.liquid
Please note how Dawn uses "currentColor" as a fill or stroke color in most of their icon files. Please use the same. This way, we can always set the SVG color by assigning the "color" CSS param

2024-06-07 15:50 UTC, alex-wuffes requested changes

2024-06-07 15:50 UTC, alex-wuffes commented on templates/page.misha_test.json
@mikhail-wuffes Don't commit your preview page into Git. You can just use it in a preview theme for demo, but do not commit it

2024-06-07 15:50 UTC, alex-wuffes commented on sections/rich-text-carousel.liquid
It's great that you [have](https://tppr.me/DhFiCN) a preview of this section. But it's not quite there. 
Look how they use [dummy images](https://tppr.me/lYcihp) in some of their section previews. Do the same. Fix for every section if needed

2024-06-07 15:50 UTC, alex-wuffes commented on templates/page.misha_test.json
Also, there's no need to use a separate page for Demo-ing the new sections. Just add them to the homepage.

2024-06-22 21:29 UTC, mikhail-wuffes commented on assets/component-image-with-text.css
> +  left: unset !important;
fixed

2024-06-22 21:30 UTC, mikhail-wuffes commented on sections/rich-text-carousel.liquid
> +              {% endif %}
fixed

2024-06-22 21:30 UTC, mikhail-wuffes commented on assets/component-image-with-text.css
> +
fixed

2024-06-22 21:31 UTC, mikhail-wuffes commented on assets/component-image-with-text.css
> +
fixed

2024-06-22 21:33 UTC, mikhail-wuffes commented on assets/component-image-with-text.css
> +  }
fixed (if I got it right)

2024-06-22 21:38 UTC, mikhail-wuffes commented on assets/component-image-with-text.css
> +  display: block !important;
fixed

2024-06-22 21:39 UTC, mikhail-wuffes commented on assets/global.js
> +    console.log("clicked - " +this.slider)
fixed

2024-06-22 21:40 UTC, mikhail-wuffes commented on assets/section-featured-collection.css
> +
fixed

2024-06-22 21:41 UTC, mikhail-wuffes commented on sections/featured-collection.liquid
> +            aria-label="{{ 'general.slider.name' | t }}"
fixed

2024-06-22 21:48 UTC, mikhail-wuffes commented on sections/image-with-text.liquid
> +              </div>
fixed

2024-06-22 21:51 UTC, mikhail-wuffes commented on sections/image-with-text.liquid
>                    <p
i have only 2 sections with blocks, so there was only 1 place to fix it (i guess)

2024-06-22 22:19 UTC, mikhail-wuffes commented on snippets/card-product.liquid
fixed

2024-06-22 22:39 UTC, mikhail-wuffes commented on snippets/icon-minus-circle.liquid
@alex-wuffes do you mean we need to set the color param in style asset? if so how can we access color_scheme?

2024-06-22 22:42 UTC, mikhail-wuffes commented on templates/page.misha_test.json
in this case we can have conflicts in future, as all devs will have different data_settings. I was thinking about deleting it once the QA & CR are passed. But we could add it to gitignore, right?

2024-06-22 22:44 UTC, mikhail-wuffes commented on sections/rich-text-carousel.liquid
@alex-wuffes rich-text-carousel section doesn't have any images. Or did I get sth. wrong?

2024-06-28 16:23 UTC, alex-wuffes commented on snippets/card-product.liquid
> +                sizes="(min-width: {{ settings.page_width }}px) {{ settings.page_width | minus: 30 | minus: 30 | minus: 4 | times: 0.8 }}px, (min-width: 990px) calc((100vw - 30px - 30px - 4px) / 4 *
On min-width: 1200px - you set more than 900px for image that is actually 300px in size https://tppr.me/ZjSk43.
Mish, I think that was a mistake to use a product card here, since it's not well-adapted for your section. 

I'm still not against continuing using it, but we have to fix these sizes.
Please, review all image sizes in sections you've done (at least on mobile and desktop)

2024-06-28 16:23 UTC, alex-wuffes commented on snippets/icon-minus-circle.liquid
@mikhail-wuffes No, that's not exactly what I've meant. https://www.loom.com/share/1d0ceca2ac8b43688bb4a531395fe205?sid=536f0a93-3203-4145-8210-bc557921e4b1

2024-06-28 16:30 UTC, alex-wuffes commented on templates/page.misha_test.json
@mikhail-wuffes You may just apply these for your theme preview. And just don't submit it to github. Applying gitignore may be a smart idea, but I'm not sure if the GitHub integration for themes will work properly (we'll get to this later)

2024-06-28 16:31 UTC, alex-wuffes commented on sections/rich-text-carousel.liquid
@mikhail-wuffes I believe it has https://tppr.me/a2ojRB

2024-07-04 16:59 UTC, mikhail-wuffes commented on assets/component-image-with-text.css
> +  left: unset !important;
marking this as resolved

2024-07-04 17:01 UTC, mikhail-wuffes commented on snippets/icon-minus-circle.liquid
@alex-wuffes but I have SVGs that uses multiple colors. What should I do in this case?

2024-07-04 18:15 UTC, mikhail-wuffes commented on sections/rich-text-carousel.liquid
fixed

2024-07-04 18:21 UTC, mikhail-wuffes commented on snippets/card-product.liquid
> +                sizes="(min-width: {{ settings.page_width }}px) {{ settings.page_width | minus: 30 | minus: 30 | minus: 4 | times: 0.8 }}px, (min-width: 990px) calc((100vw - 30px - 30px - 4px) / 4 *
yes, my bad. This supposed to be "divided_by:4", not "minus:4".

2024-07-04 18:24 UTC, mikhail-wuffes commented on snippets/card-product.liquid
> +                sizes="(min-width: {{ settings.page_width }}px) {{ settings.page_width | minus: 30 | minus: 30 | minus: 4 | times: 0.8 }}px, (min-width: 990px) calc((100vw - 30px - 30px - 4px) / 4 *
should be fine now

2024-07-09 09:46 UTC, alex-wuffes approved these changes

2024-07-09 16:14 UTC, merged