Nav footer marquee richtext + custom section 1
Wuffes/wuffes-2.0 pull request #2
Opened 2024-06-03 17:31 UTC by jayveedev

### Asana Task link: 
- [Asana Task](https://app.asana.com/0/1206375175000843/1207248753824845/f)
### Demo links

- [Store](https://wuffes.com/?preview_theme_id=129321435271)
- [Editor](https://admin.shopify.com/store/wuffes-store/themes/129321435271/editor)

### Checklist
- [x] Tested on mobile
- [x] Tested on desktop
- [x] Requested review from QA (if applicable)

- [x] Requested approval from 1 senior dev on Github and in Asana task
- [ ] Moved task to "Code Review" status in Asana

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207473649991123

2024-06-07 15:50 UTC, alex-wuffes requested changes

2024-06-07 15:50 UTC, alex-wuffes commented on sections/marquee.liquid
Every section should have a preview (you can make this happen by using the "preset" section setting in the end of the section liquid file).
Check other sections as well, please

https://tppr.me/NuNPNE
https://tppr.me/8mpexV

2024-06-07 15:50 UTC, alex-wuffes commented on templates/index.json
Do not commit changes to templates you made just for a preview. You can leave them on a testing theme, but don't commit them into git

2024-06-07 15:50 UTC, alex-wuffes commented on sections/rich-text.liquid
> +                (min-width: 750px) calc((100vw - 130px) / 2), calc((100vw - 50px) / 2)
The "sizes" attribute is clearly wrong here. Review it and fix to reflect the actual mobile width. From my observations - at this moment it should be calc(100vw - 30px).
Also, fix other sizes in this section.

2024-06-07 15:50 UTC, alex-wuffes commented on sections/header.liquid
> +                    {% capture sizes %}(max-width: {{ settings.logo_width | times: 2 }}px) 50vw, {{ settings.logo_width }}px{% endcapture %}
Sizes don't look right here. I recorded a separate loom on this topic. 
Revise this section according to the loom provided.
https://www.loom.com/share/7aadfca1074c44258e32a5edf747dea9?sid=ef6be637-498e-4f0b-bf21-ab4054832bce

2024-06-07 15:50 UTC, alex-wuffes commented on sections/custom-1.liquid
> +        (min-width: 750px) calc((100vw - 130px) / 2), calc((100vw - 50px) / 2)
I can see you used the incorrect sizes used in dawn in all sections. Please, fix it, so sizes are correct.

2024-06-14 16:30 UTC, jayveedev commented on assets/base.css
> +  margin-left: -10px;
We only use quantity selector in the current theme. But I moved these codes to a nested selector under cart drawer just in case we decide to use cart page.

2024-06-21 17:41 UTC, jayveedev commented on sections/custom-1.liquid
> +              {%- endif -%}
Thanks! I learned how to use 'echo'

2024-06-21 18:39 UTC, jayveedev commented on sections/rich-text.liquid
> +                }}
Thanks! I'll keep line-through for now since it is not built-in and a pasted text with line-through looks weird
https://prnt.sc/3FzlkEuJz4c-

2024-06-21 19:02 UTC, jayveedev commented on locales/en.default.schema.json
> +      "blocks": {
Thought it would be practical to limit blocks to avoid escessive dom. I'll remove the limit. Thanks!

2024-06-21 19:15 UTC, jayveedev commented on sections/header.liquid
> +                    {% capture sizes %}(max-width: {{ settings.logo_width | times: 2 }}px) 50vw, {{ settings.logo_width }}px{% endcapture %}
This is amazing tutorial @alex-wuffes , thank you! It saved me the time trying to figure out what those code meant!

2024-07-19 15:44 UTC, alex-wuffes approved these changes

2024-07-22 17:45 UTC, merged