Collection product grid
Wuffes/wuffes-2.0 pull request #5
Opened 2024-07-04 22:06 UTC by jayveedev

### Asana Task link:

- [Asana Task](url)

### Demo links
[Asana task url](https://app.asana.com/0/1206375175000843/1207248759862717/f)

- [Store](https://wuffes.com/collections/shop-all?preview_theme_id=130195783815)
- [Editor](https://admin.shopify.com/store/wuffes-store/themes/130195783815/editor?previewPath=%2Fcollections%2Fshop-all)

### Checklist

- [x] Tested on mobile
- [x] Tested on desktop
- [x] Requested review from QA (if applicable)

- [x] Requested approval from 1 senior dev on Github and in Asana task
- [x] Moved task to "QA" status in Asana

2024-07-16 15:47 UTC, alex-wuffes requested changes

2024-07-16 15:47 UTC, alex-wuffes commented on snippets/card-product-custom.liquid
> +          assign sizes = '(max-width: 990px) calc(50vw), (max-width: 990px) calc(25vw)'
Few issues with this block. 
1. Media query is max-width: 990px twice (just a typo)
2. There's no media query for the situation when container gets a fixed width.
https://www.loom.com/share/cb97d01dd3a14cfc9d42878ff330295e?sid=dfbfb8ec-072d-4709-8292-97841de805ec

2024-07-16 15:47 UTC, alex-wuffes commented on sections/main-collection-product-grid.liquid
> +    },
We use both the "custom product card" and "product card" section settings parameters right now. It may be not very clear for people who will be working with this section. My best advice will be to remove the extra section settings you do not use and leave only one settings section.
https://www.loom.com/share/925a71c939e04578a229f801cb95af07?sid=ec43b4f5-21aa-4011-bea5-d65e45185ec7

2024-07-16 15:47 UTC, alex-wuffes commented on sections/main-collection-product-grid.liquid
>      }
We can only leave the image picker setting with the info. You can decide if you want to show a promo badge image or not by looking if promo badge image is set

```suggestion
    {
      "type": "image_picker",
      "id": "promo_badge_img",
      "label": "Promo badge image",
      "info": "Utilizes product metafield: prerebrand_collection_filter.best_seller.value"
    }
```

2024-07-16 15:47 UTC, alex-wuffes commented on sections/main-collection-product-grid.liquid
>  {{ 'component-card.css' | asset_url | stylesheet_tag }}
In case we don't use component-card anymore - remove this stylesheet

2024-07-18 16:57 UTC, jayveedev commented on snippets/card-product-custom.liquid
> +            echo promo_badge_img | image_url: width: '88' | image_tag: widths: promo_badge_img_widths, sizes: promo_badge_img_sizes, class: 'card__inner_promo_badge_img'
another awesome tutorial, thanks @alex-wuffes !

2024-07-18 18:06 UTC, jayveedev commented on sections/main-collection-product-grid.liquid
> +    },
Worried removing the other section settings would just destroy the default card.
Extra settings that are not used in custom product card is rmeoved.

2024-07-18 18:27 UTC, jayveedev commented on sections/main-collection-product-grid.liquid
>  {{ 'component-card.css' | asset_url | stylesheet_tag }}
Done, I also removed other assets that may no longer be relevant for this section

2024-07-19 15:30 UTC, alex-wuffes requested changes

2024-07-19 15:30 UTC, alex-wuffes commented on snippets/card-product-custom.liquid
> +          assign sizes = '(max-width: 749px) calc((100vw - 58px) / 2), (min-width: 750px) calc((100vw - (25.8vw + 28px)) / 2), (min-width: 990px) calc((100vw - 144px) / 4), (min-width: 1200px) 264px'
```suggestion
          assign sizes = '(max-width: 749px) calc((100vw - 58px) / 2), (min-width: 750px) calc((100vw - (25.8vw + 28px)) / 2), (min-width: 990px) calc((100vw - 144px) / 4), (min-width: 1200px) 264px'
```

@jayveedev One more small improvement. You can use not-hardcoded layout width. So settings.page_width instead of 1200px and settings.page_width | divided_by: 4 | minus: 36 instead of 264px

2024-07-19 16:32 UTC, jayveedev commented on snippets/card-product-custom.liquid
> +          assign sizes = '(max-width: 749px) calc((100vw - 58px) / 2), (min-width: 750px) calc((100vw - (25.8vw + 28px)) / 2), (min-width: 990px) calc((100vw - 144px) / 4), (min-width: 1200px) 264px'
Done :)

I had to create a separate variable to handle the image width at 1200px because it just doesn't work if I inlcude the calculations in the assign tag.

```
assign desktop_size = settings.page_width | divided_by: 4 | minus: 36 | append: 'px'

assign widths = '130, 260, 390, 575, 860'
assign sizes = '(max-width: 749px) calc((100vw - 58px) / 2), (min-width: 750px) calc((100vw - (25.8vw + 28px)) / 2), (min-width: 990px) calc((100vw - 144px) / 4), (min-width: ' | append: settings.page_width | append: 'px) ' | append: desktop_size
```

2024-07-19 16:39 UTC, alex-wuffes commented on snippets/card-product-custom.liquid
> +          assign sizes = '(max-width: 749px) calc((100vw - 58px) / 2), (min-width: 750px) calc((100vw - (25.8vw + 28px)) / 2), (min-width: 990px) calc((100vw - 144px) / 4), (min-width: 1200px) 264px'
@jayveedev Amazing!

2024-07-19 16:39 UTC, alex-wuffes approved these changes

2024-07-22 17:53 UTC, merged